name: unit-test
on: [push]
jobs:
  ci:
    name: CI
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install docker
       run: |
         brew install docker docker-machine docker-compose
         mkdir -p ~/.docker/cli-plugins
         ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
         bash ./unit_test.sh
