name: unit-test
on: [push]
jobs:
  ci:
    name: CI
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v2
     - name: Install docker
       run: |
         mkdir -p ~/.docker/machine/cache
         curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
         brew install docker docker-machine
     - name: Checkout code
       uses: actions/checkout@v3
     - name: unit-test
       run: bash ./unit_test.sh
