name: unit-test
on: [push]
jobs:
  ci:
    name: CI
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install docker
       run: |
         brew install docker docker-machine
         sudo docker --version
         sudo docker-compose --version
