name: unit-test
on: [push]
jobs:
  ci:
    name: CI
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v2
     - name: Install docker
       run: |
         export DOCKER_HOST="unix://$HOME/.colima/docker.sock"
         brew install docker docker-compose colima
     - name: Checkout code
       uses: actions/checkout@v3
     - name: unit-test
       run: bash ./unit_test.sh
