name: unit-test
on: [push]
jobs:
  ci:
    name: CI
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install docker
       run: |
         export HOMEBREW_NO_INSTALL_CLEANUP=1
         brew install docker docker-machine docker-compose colima
         sudo docker --version
         sudo docker-compose --version
         colima start
         su
         sudo docker-compose build
         sudo docker-compose up -d
