name: unit-test
on: [push]
jobs:
  ci:
    name: CI
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v2
     - name: Install docker
       run: |
         brew install docker docker-machine docker-compose
     - name: Checkout code
       uses: actions/checkout@v3
     - name: unit-test
       run: bash ./unit_test.sh
