name: unit-test
on: [push]
jobs:
  ci:
    name: CI
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install docker
       run: |
         brew install docker docker-machine docker-compose colima
         export DOCKER_HOST="unix://$HOME/.colima/docker.sock"
         sudo docker --version
         sudo docker-compose --version
         sudo ll /var/run
